-- Migration script to populate the database with initial artifact data
-- Run this script after creating the schema

-- Insert initial artifacts (80 total across 4 slots)
INSERT INTO artifacts (name, description, slot) VALUES
-- Slot 1 (20 artifacts)
('Boots of the Forgotten', NULL, 1),
('Greaves of Ancient Power', NULL, 1),
('Treads of the Void Walker', NULL, 1),
('Sabatons of the Iron Will', NULL, 1),
('Boots of Eternal Flame', NULL, 1),
('Greaves of the Storm', NULL, 1),
('Treads of the Shadow', NULL, 1),
('Sabatons of Light', NULL, 1),
('Boots of the Wanderer', NULL, 1),
('Greaves of the Titan', NULL, 1),
('Treads of Swift Justice', NULL, 1),
('Sabatons of the Guardian', NULL, 1),
('Boots of the Hunter', NULL, 1),
('Greaves of the Mystic', NULL, 1),
('Treads of the Warrior', NULL, 1),
('Sabatons of the Sage', NULL, 1),
('Boots of the Ranger', NULL, 1),
('Greaves of the Paladin', NULL, 1),
('Treads of the Rogue', NULL, 1),
('Sabatons of the Monk', NULL, 1),

-- Slot 2 (20 artifacts)
('Gauntlets of the Forgotten', NULL, 2),
('Gloves of Ancient Power', NULL, 2),
('Handguards of the Void Walker', NULL, 2),
('Gauntlets of the Iron Will', NULL, 2),
('Gloves of Eternal Flame', NULL, 2),
('Handguards of the Storm', NULL, 2),
('Gauntlets of the Shadow', NULL, 2),
('Gloves of Light', NULL, 2),
('Handguards of the Wanderer', NULL, 2),
('Gauntlets of the Titan', NULL, 2),
('Gloves of Swift Justice', NULL, 2),
('Handguards of the Guardian', NULL, 2),
('Gauntlets of the Hunter', NULL, 2),
('Gloves of the Mystic', NULL, 2),
('Handguards of the Warrior', NULL, 2),
('Gauntlets of the Sage', NULL, 2),
('Gloves of the Ranger', NULL, 2),
('Handguards of the Paladin', NULL, 2),
('Gauntlets of the Rogue', NULL, 2),
('Gloves of the Monk', NULL, 2),

-- Slot 3 (20 artifacts)
('Helm of the Forgotten', NULL, 3),
('Crown of Ancient Power', NULL, 3),
('Mask of the Void Walker', NULL, 3),
('Helm of the Iron Will', NULL, 3),
('Crown of Eternal Flame', NULL, 3),
('Mask of the Storm', NULL, 3),
('Helm of the Shadow', NULL, 3),
('Crown of Light', NULL, 3),
('Mask of the Wanderer', NULL, 3),
('Helm of the Titan', NULL, 3),
('Crown of Swift Justice', NULL, 3),
('Mask of the Guardian', NULL, 3),
('Helm of the Hunter', NULL, 3),
('Crown of the Mystic', NULL, 3),
('Mask of the Warrior', NULL, 3),
('Helm of the Sage', NULL, 3),
('Crown of the Ranger', NULL, 3),
('Mask of the Paladin', NULL, 3),
('Helm of the Rogue', NULL, 3),
('Crown of the Monk', NULL, 3),

-- Slot 4 (20 artifacts)
('Armor of the Forgotten', NULL, 4),
('Plate of Ancient Power', NULL, 4),
('Vestments of the Void Walker', NULL, 4),
('Armor of the Iron Will', NULL, 4),
('Plate of Eternal Flame', NULL, 4),
('Vestments of the Storm', NULL, 4),
('Armor of the Shadow', NULL, 4),
('Plate of Light', NULL, 4),
('Vestments of the Wanderer', NULL, 4),
('Armor of the Titan', NULL, 4),
('Plate of Swift Justice', NULL, 4),
('Vestments of the Guardian', NULL, 4),
('Armor of the Hunter', NULL, 4),
('Plate of the Mystic', NULL, 4),
('Vestments of the Warrior', NULL, 4),
('Armor of the Sage', NULL, 4),
('Plate of the Ranger', NULL, 4),
('Vestments of the Paladin', NULL, 4),
('Armor of the Rogue', NULL, 4),
('Plate of the Monk', NULL, 4);

-- Verify the data was inserted correctly
SELECT slot, COUNT(*) as count FROM artifacts GROUP BY slot ORDER BY slot;